# Generated by Django 5.0.6 on 2024-06-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnemyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("dc", models.IntegerField(verbose_name="Difficulty Class")),
                ("start_at", models.DateTimeField(verbose_name="Start")),
                ("end_at", models.DateTimeField(verbose_name="End")),
            ],
        ),
        migrations.CreateModel(
            name="GameCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("structure_enemies", models.JSONField(verbose_name="Enemies")),
                ("structure_npcs", models.JSONField(verbose_name="NPCs")),
            ],
        ),
        migrations.CreateModel(
            name="NPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("area", models.FloatField(verbose_name="Area")),
                (
                    "strc_type",
                    models.CharField(
                        choices=[
                            ("PL", "Plain"),
                            ("MT", "Mountains"),
                            ("RD", "Road"),
                            ("DG", "Dungeon"),
                        ],
                        max_length=2,
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enemy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("hp", models.FloatField(verbose_name="Hit points")),
                ("min_power", models.FloatField(verbose_name="Minimum Power")),
                ("max_power", models.FloatField(verbose_name="Maximum Power")),
                (
                    "enm_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.enemytype",
                    ),
                ),
            ],
        ),
    ]
