# Generated by Django 5.0.6 on 2024-06-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_gamestructure_structure_enemies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="dc",
            field=models.FloatField(verbose_name="Difficulty Class"),
        ),
    ]
