# Generated by Django 5.0.6 on 2024-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_game_dc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamestructure",
            name="structure_enemies",
            field=models.JSONField(default={"1": 0}, verbose_name="Enemies"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gamestructure",
            name="structure_npcs",
            field=models.JSONField(default={}, verbose_name="NPCs"),
            preserve_default=False,
        ),
    ]
